############################################################
# Dockerfile for website build using jekyll, hugo, or mkdocs
############################################################
## Patched version from https://github.com/sbamin/sitebuilder/releases
## depending on patches, can be used for both, amd64 and arm64

FROM sbamin/sitebuilder:1.5.6

## For questions, visit https:
MAINTAINER "Samirkumar Amin" <tweet:sbamin; sbamin.com/contact>

## NOTE: installing beta version of mkdocs-material with blog support.
LABEL version="1.5.6p1" \
	mode="sitebuilder-1.5.6p1" \
	description="docker image to build jekyll, hugo or mkdocs supported website" \
	website="https://github.com/sbamin/sitebuilder" \
	issues="https://github.com/sbamin/sitebuilder/issues"

## run apt-get non-interactive
## https://stackoverflow.com/a/56569081/1243763
ARG DEBIAN_FRONTEND=noninteractive

#### Python 3 venv at /opt/venv/bin ####
ENV PATH="/opt/venv/bin:$PATH"

## patch commands
RUN pip3 install --upgrade pip && \
	pip3 install --upgrade "mkdocs-material[imaging,recommended,git]" && \
	pip3 install --upgrade markdown pygments fontawesome_markdown pymdown-extensions && \
	pip3 install --upgrade mkdocs mkdocs-material mkdocs-git-revision-date-plugin  mkdocs-git-revision-date-localized-plugin mkdocs-minify-plugin mkdocs-redirects pymdown-extensions mkdocs-macros-plugin mike mkdocs-git-authors-plugin mkdocs-glightbox && \
	pip3 install --upgrade mkdocstrings mkdocstrings-python mkdocstrings-shell

## cleanup cache
RUN pip3 cache purge && \
	cd /scratch && \
	bundle clean --force && \
	apt-get clean && \
	rm -f go"${mygo}".linux-amd64.tar.gz && \
	rm -rf /var/lib/apt/lists/*

ENV GOPATH="/opt/go"

## empty dir where user volume should be mounted
## to run jekyll related commands
WORKDIR /web

ENV PATH /opt/venv/bin:/usr/local/bundle/bin:/usr/local/bundle/gems/bin:/usr/local/go/bin:/opt/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

#### expose ports for jekyll, mkdocs, and hugo serve command ####
EXPOSE 4000
EXPOSE 8000
EXPOSE 1313

ENTRYPOINT []
CMD []

## END ##

